import { Form } from './FORMS.js'
import { getItems } from './cardsAction.js'
const filterForm = new Form('filter')
const filterWrapper = document.querySelector('#filter-wrapper')
filterWrapper.append(filterForm.form)

const data = [
    { name: 'Breanne', title: 'Accountant II', heartDiseases: 'Carbon Dioxide', lastVisit: 'Bortol', isClosed: false },
    { name: 'Lucille', title: 'Web Developer IV', heartDiseases: 'DIMETHICONE', lastVisit: 'Eskrick', isClosed: true },
    { name: 'Kristy', title: 'Engineer II', heartDiseases: 'ALCOHOL', lastVisit: 'Camacho', isClosed: false },
    { name: 'Merilyn', title: 'Account Coordinator', heartDiseases: 'BENZALKONIUM CHLORIDE', lastVisit: 'Dowty', isClosed: false },
    { name: 'Winslow', title: 'Programmer Analyst II', heartDiseases: 'OCTINOXATE, OCTISALATE', lastVisit: 'Watmough', isClosed: false },
    { name: 'Dulcinea', title: 'Financial Analyst', heartDiseases: 'OCTINOXATE and TITANIUM DIOXIDE', lastVisit: 'Tallboy', isClosed: true },
    { name: 'Jeddy', title: 'Developer III', heartDiseases: 'insulin glargine', lastVisit: 'Castro', isClosed: false },
    { name: 'Julia', title: 'Assistant Professor', heartDiseases: 'Poplar', lastVisit: 'Dulieu', isClosed: true },
    { name: 'Bernie', title: 'Dental Hygienist', heartDiseases: 'OCTINOXATE and TITANIUM DIOXIDE', lastVisit: "O'Currine", isClosed: true },
    { name: 'Hagan', title: 'Programmer I', heartDiseases: 'pancrelipase', lastVisit: 'Rushman', isClosed: true },
    { name: 'Darcee', title: 'VP Product Management', heartDiseases: 'TITANIUM DIOXIDE', lastVisit: 'Ollis', isClosed: false },
    {
        name: 'Lucien',
        title: 'Programmer Analyst III',
        heartDiseases:
            'rSomatotropin, rIGF-I, rIGF-II, RNA, DNA,Glandula Suprarenalis Suis, Hepar Suis, Pituitarium Posterium, Thymus, Thyroidinum, Placenta Totalis Suis, Orchitinum, Abrotanum, Anacard Or, Arsenicum Alb, Baryta Carb, Baryta Mur, Calc Carb, Calc Phos, Ferrum Met, Fucus, Hekla, Hellebor Nig, Ignatia, Lycopodium, Nicotinamidium, Secale, Silicea, Cobaltum Met, Lithium Carb, Mag Phos, Mang Acet, Kali Phos, Selenium Met, Zinc Met.',
        lastVisit: 'Foy',
        isClosed: true,
    },
    { name: 'Cristiano', title: 'Health Coach IV', heartDiseases: 'fluocinonide', lastVisit: 'Casburn', isClosed: false },
    { name: 'Rey', title: 'Senior Quality Engineer', heartDiseases: 'Butalbital, Aspirin and Caffeine', lastVisit: 'McCulloch', isClosed: false },
    { name: 'Devondra', title: 'Internal Auditor', heartDiseases: 'SIMETHICONE', lastVisit: 'Inglefield', isClosed: false },
    { name: 'Julianne', title: 'Web Developer II', heartDiseases: 'Larch,', lastVisit: 'Elis', isClosed: true },
    { name: 'Montgomery', title: 'Research Nurse', heartDiseases: 'Yellow Onion', lastVisit: 'Sheal', isClosed: true },
    { name: 'Dorise', title: 'Internal Auditor', heartDiseases: 'Dexamethasone Sodium Phosphate', lastVisit: 'Gowar', isClosed: false },
    { name: 'Daffy', title: 'Research Associate', heartDiseases: 'Pumpkin', lastVisit: 'Laundon', isClosed: false },
    { name: 'Lari', title: 'Tax Accountant', heartDiseases: 'Diphenhydramine Hydrochloride', lastVisit: 'Chaperling', isClosed: true },
    { name: 'Magdaia', title: 'Administrative Assistant I', heartDiseases: 'Miconazole Nitrate', lastVisit: 'Highton', isClosed: true },
    { name: 'Norris', title: 'Paralegal', heartDiseases: 'TITANIUM DIOXIDE, ZINC OXIDE', lastVisit: 'Spikeings', isClosed: false },
    { name: 'Oona', title: 'Office Assistant II', heartDiseases: 'Acetaminophen', lastVisit: 'Vearncombe', isClosed: false },
    { name: 'Joyann', title: 'Food Chemist', heartDiseases: 'triclosan', lastVisit: 'Counihan', isClosed: false },
    { name: 'Simonne', title: 'Paralegal', heartDiseases: 'Doxylamine succinate', lastVisit: 'Rolf', isClosed: true },
    { name: 'Berna', title: 'Geological Engineer', heartDiseases: 'Salicylic Acid', lastVisit: 'Dahlbom', isClosed: true },
    { name: 'Jody', title: 'Information Systems Manager', heartDiseases: 'SELENIUM SULFIDE', lastVisit: 'Paolo', isClosed: false },
    { name: 'Hilton', title: 'Research Associate', heartDiseases: 'Pantoprazole Sodium', lastVisit: 'Dearnaley', isClosed: false },
    { name: 'Hermie', title: 'Assistant Manager', heartDiseases: 'ETHYL ALCOHOL', lastVisit: 'MacCarlich', isClosed: false },
    { name: 'Risa', title: 'Marketing Manager', heartDiseases: 'Eucalyptol, menthol, methyl salicylate, thymol', lastVisit: 'Savin', isClosed: true },
    { name: 'Channa', title: 'VP Product Management', heartDiseases: 'Sulfamethoxazole and Trimethoprim', lastVisit: 'Blacksland', isClosed: false },
    { name: 'Lois', title: 'Marketing Manager', heartDiseases: 'Fluoxetine Hydrochloride', lastVisit: 'Snoxill', isClosed: false },
    { name: 'Elyn', title: 'Electrical Engineer', heartDiseases: 'SILICON DIOXIDE', lastVisit: 'Oganesian', isClosed: true },
    { name: 'Inger', title: 'Administrative Assistant II', heartDiseases: 'Lisinopril', lastVisit: 'Tirkin', isClosed: true },
    { name: 'Cathi', title: 'Actuary', heartDiseases: 'Clotrimazole', lastVisit: 'Lucks', isClosed: true },
    { name: 'Mair', title: 'Physical Therapy Assistant', heartDiseases: 'Candesartan Cilexetil and Hydrochlorothiazide', lastVisit: 'Paff', isClosed: true },
    { name: 'Free', title: 'Data Coordiator', heartDiseases: 'Acetaminophen, Aspirin and caffeine', lastVisit: 'Whyke', isClosed: true },
    { name: 'Sallyanne', title: 'Cost Accountant', heartDiseases: 'SULFACETAMIDE SODIUM', lastVisit: 'Truggian', isClosed: true },
    { name: 'Teresita', title: 'Administrative Assistant I', heartDiseases: 'Povidone-Iodine', lastVisit: 'Loosely', isClosed: true },
    { name: 'Alisa', title: 'Biostatistician IV', heartDiseases: 'Acetaminophen', lastVisit: 'Croose', isClosed: true },
    { name: 'Ana', title: 'Food Chemist', heartDiseases: 'Energize', lastVisit: 'Whipp', isClosed: false },
    { name: 'Rudolf', title: 'Quality Control Specialist', heartDiseases: 'DOCUSATE SODIUM', lastVisit: 'Cheke', isClosed: false },
    { name: 'Janette', title: 'Assistant Manager', heartDiseases: 'loratadine and pseudoephedrine', lastVisit: 'Caw', isClosed: false },
    { name: 'Rozanna', title: 'Design Engineer', heartDiseases: 'Simethicone', lastVisit: 'Richardet', isClosed: true },
    { name: 'Christoph', title: 'Health Coach III', heartDiseases: 'Oxycodone and Acetaminophen', lastVisit: 'Wort', isClosed: true },
    { name: 'Valentijn', title: 'Legal Assistant', heartDiseases: 'SALICYLIC ACID', lastVisit: 'Reynalds', isClosed: false },
    { name: 'Brigitta', title: 'Automation Specialist I', heartDiseases: 'RIFAXIMIN', lastVisit: 'Dominico', isClosed: true },
    { name: 'Alford', title: 'Librarian', heartDiseases: 'Fluoride', lastVisit: 'Pistol', isClosed: false },
    { name: 'Gilbert', title: 'Technical Writer', heartDiseases: 'drospirenone and ethinyl estradiol', lastVisit: 'Kitchin', isClosed: false },
    { name: 'Jaquelin', title: 'Research Associate', heartDiseases: 'TITANIUM DIOXIDE', lastVisit: 'Alcido', isClosed: false },
    { name: 'Emyle', title: 'Sales Associate', heartDiseases: 'Ibuprofen, Pseudoephedrine HCl', lastVisit: 'Warton', isClosed: true },
    { name: 'Maury', title: 'Dental Hygienist', heartDiseases: 'Argentum Quartz', lastVisit: 'Severy', isClosed: true },
    { name: 'Humfried', title: 'Information Systems Manager', heartDiseases: 'nifedipine', lastVisit: 'Linger', isClosed: false },
    { name: 'Oliviero', title: 'Chemical Engineer', heartDiseases: 'Famotidine', lastVisit: 'Allender', isClosed: true },
    { name: 'Miriam', title: 'VP Sales', heartDiseases: 'atorvastatin calcium', lastVisit: 'Vasiltsov', isClosed: false },
    { name: 'Nathanial', title: 'Geologist III', heartDiseases: 'Chlordiazepoxide Hydrochloride and Clidinium Bromide', lastVisit: 'Westell', isClosed: true },
    { name: 'Giovanna', title: 'VP Quality Control', heartDiseases: 'Tall Ragweed', lastVisit: 'Bednall', isClosed: true },
    { name: 'Malvin', title: 'VP Quality Control', heartDiseases: 'Willow,', lastVisit: 'Bricklebank', isClosed: true },
    { name: 'Nessy', title: 'VP Accounting', heartDiseases: 'Octinoxate and Oxybenzone', lastVisit: 'Hayes', isClosed: true },
    { name: 'Isabella', title: 'Staff Scientist', heartDiseases: 'Palmers Amaranth', lastVisit: 'Buffy', isClosed: true },
    { name: 'Helli', title: 'Research Assistant III', heartDiseases: 'TITANIUM DIOXIDE, ZINC OXIDE, ARBUTIN, ADENOSINE', lastVisit: 'Pohlak', isClosed: true },
    { name: 'Shirley', title: 'Help Desk Operator', heartDiseases: 'Neomycin sulfate, Polymyxin B Sulfate, and Dexamethasone', lastVisit: 'Thornham', isClosed: false },
    { name: 'Elfreda', title: 'Geologist II', heartDiseases: 'Captopril', lastVisit: 'Woodwin', isClosed: false },
    { name: 'Cairistiona', title: 'Systems Administrator IV', heartDiseases: 'ETHYL ALCOHOL', lastVisit: 'Darrel', isClosed: true },
    { name: 'Dot', title: 'Web Designer IV', heartDiseases: 'TITANIUM DIOXIDE and OCTINOXATE', lastVisit: 'Armistead', isClosed: false },
    { name: 'Willem', title: 'Staff Scientist', heartDiseases: 'Duloxetine', lastVisit: 'Dutteridge', isClosed: false },
    { name: 'Georgeta', title: 'Business Systems Development Analyst', heartDiseases: 'Kiwi', lastVisit: 'Cubbit', isClosed: true },
    { name: 'Gunner', title: 'Recruiter', heartDiseases: 'ETHYL ALCOHOL', lastVisit: 'Vallintine', isClosed: true },
    { name: 'Nannette', title: 'Senior Cost Accountant', heartDiseases: 'Beef', lastVisit: 'Bendle', isClosed: false },
    { name: 'Penny', title: 'Analyst Programmer', heartDiseases: 'Quinapril Hydrochloride and Hydrochlorothiazide', lastVisit: 'Tebboth', isClosed: true },
    { name: 'Valida', title: 'VP Accounting', heartDiseases: 'Fluphenazine Hydrochloride', lastVisit: 'Simkiss', isClosed: false },
    { name: 'Ninnette', title: 'Quality Control Specialist', heartDiseases: 'Cefoxitin', lastVisit: 'Klaassens', isClosed: true },
    { name: 'Verne', title: 'Programmer Analyst IV', heartDiseases: 'amlodipine besylate and benazepril hydrochloride', lastVisit: 'Pamplin', isClosed: true },
    { name: 'Nelia', title: 'Automation Specialist II', heartDiseases: 'Titanium Dioxide', lastVisit: 'Janku', isClosed: false },
    { name: 'Noelle', title: 'Environmental Tech', heartDiseases: 'Diclofenac Sodium', lastVisit: 'Packman', isClosed: true },
    { name: 'Karlotte', title: 'Sales Representative', heartDiseases: 'Ibuprofen', lastVisit: 'Domenichini', isClosed: false },
    { name: 'Candy', title: 'Senior Financial Analyst', heartDiseases: 'Russian Olive', lastVisit: 'Kerbler', isClosed: false },
    { name: 'Ephraim', title: 'Biostatistician I', heartDiseases: 'glipizide and metformin hydrochloride', lastVisit: 'Twyning', isClosed: true },
    {
        name: 'Angie',
        title: 'Dental Hygienist',
        heartDiseases: 'Arsenicum Album, Hepar Sulphuris Calcareum, Kali Bichromicum, Lycopodium Clavatum, Mercurius Solubilis',
        lastVisit: 'Sorey',
        isClosed: true,
    },
    { name: 'Cecilia', title: 'Engineer IV', heartDiseases: 'Prednisone', lastVisit: 'Buchan', isClosed: false },
    { name: 'Barris', title: 'Product Engineer', heartDiseases: 'Promethazine Hydrochloride', lastVisit: 'Soden', isClosed: true },
    { name: 'Aldridge', title: 'Librarian', heartDiseases: 'AMMONIUM LACTATE', lastVisit: 'Bacop', isClosed: true },
    { name: 'Ladonna', title: 'Structural Analysis Engineer', heartDiseases: 'didanosine', lastVisit: 'Trenear', isClosed: false },
    { name: 'Hedwiga', title: 'Budget/Accounting Analyst II', heartDiseases: 'Phenylephrine HCl', lastVisit: 'Garlic', isClosed: false },
    {
        name: 'Launce',
        title: 'Quality Control Specialist',
        heartDiseases:
            'Aesculus carnea, flos, allium sativum, Ambra grisea, Baryta carbonica, Ceratostigma willmottianum, flos, Conium maculatum, Graphites, Helianthus annuus, Juglans regia, flos, Kali phosphoricum, Larix decidua, flos, Mancinella, Pulsatilla, Viola odorata, Xanthoxylum fraxineum',
        lastVisit: 'Stapells',
        isClosed: false,
    },
    { name: 'Zuzana', title: 'Product Engineer', heartDiseases: 'Avobenzone, Octisalate and Octocrylene', lastVisit: 'Whymark', isClosed: false },
    { name: 'Shermy', title: 'VP Quality Control', heartDiseases: 'methsuximide', lastVisit: 'Brocklesby', isClosed: false },
    { name: 'Marion', title: 'Chemical Engineer', heartDiseases: 'Betula Argentum', lastVisit: 'Reitenbach', isClosed: true },
    { name: 'Alla', title: 'Civil Engineer', heartDiseases: 'TITANIUM DIOXIDE', lastVisit: 'Studart', isClosed: true },
    { name: 'Shanta', title: 'Structural Engineer', heartDiseases: 'Diltiazem Hydrochloride', lastVisit: 'Heal', isClosed: false },
    { name: 'Casey', title: 'Dental Hygienist', heartDiseases: 'Helium', lastVisit: 'Enterlein', isClosed: false },
    { name: 'Tandy', title: 'Budget/Accounting Analyst III', heartDiseases: 'penicillium chrysogenum var. chrysogenum', lastVisit: 'Klempke', isClosed: true },
    { name: 'Tootsie', title: 'Teacher', heartDiseases: 'SODIUM FLUORIDE', lastVisit: 'Monelli', isClosed: false },
    { name: 'Sandro', title: 'Dental Hygienist', heartDiseases: 'Vinorelbine', lastVisit: "O'Dowd", isClosed: false },
    { name: 'Tedie', title: 'Environmental Specialist', heartDiseases: 'SODIUM FLUORIDE', lastVisit: 'Addeycott', isClosed: true },
    { name: 'Corty', title: 'Business Systems Development Analyst', heartDiseases: 'Acetaminophen', lastVisit: 'Foxon', isClosed: true },
    { name: 'Emmalyn', title: 'Business Systems Development Analyst', heartDiseases: 'Dexbrompheniramine Maleate, Pseudoephedrine', lastVisit: 'Onslow', isClosed: true },
    { name: 'Carmella', title: 'Senior Cost Accountant', heartDiseases: 'Hydrogen Peroxide', lastVisit: 'Tomasini', isClosed: false },
    { name: 'Marion', title: 'Environmental Specialist', heartDiseases: 'Calcium Acetate', lastVisit: 'Caistor', isClosed: false },
    { name: 'Conroy', title: 'Budget/Accounting Analyst IV', heartDiseases: 'Acetaminophen, Dextromethorphan Hydrobromide, Phenylephrine Hydrochloride', lastVisit: 'Farnin', isClosed: true },
    { name: 'Dionysus', title: 'Engineer II', heartDiseases: 'Zinc Oxide, Titanium Dioxide', lastVisit: 'Watkins', isClosed: false },
    { name: 'Haze', title: 'Programmer Analyst I', heartDiseases: 'Aluminum Zirconium Tetrachlorohydrex GLY', lastVisit: 'Barwick', isClosed: false },
    { name: 'Angelina', title: 'Cost Accountant', heartDiseases: 'Oxymorphone hydrochloride', lastVisit: 'Arpe', isClosed: false },
    { name: 'Marietta', title: 'Web Designer II', heartDiseases: 'KE-53PS Gel Hand Sanitizer', lastVisit: 'Cleynman', isClosed: false },
    { name: 'Harrison', title: 'Editor', heartDiseases: 'ANTIMONY POTASSIUM TARTRATE', lastVisit: 'Lovelady', isClosed: false },
    {
        name: 'Ealasaid',
        title: 'Research Nurse',
        heartDiseases: 'IPECAC, BRYONIA ALBA ROOT, SPONGIA OFFICINALIS SKELETON, ROASTED, PHOSPHORUS, CAUSTICUM, DROSERA ROTUNDIFOLIA, and RUMEX CRISPUS ROOT',
        lastVisit: 'Garden',
        isClosed: false,
    },
    { name: 'Katti', title: 'Systems Administrator II', heartDiseases: 'hydrocodone bitartrate', lastVisit: 'Tocque', isClosed: true },
    { name: 'Caterina', title: 'Budget/Accounting Analyst IV', heartDiseases: 'Pyrithione Zinc', lastVisit: 'Ivic', isClosed: false },
    { name: 'Blondelle', title: 'Health Coach I', heartDiseases: 'ETHYL ALCOHOL', lastVisit: 'Oattes', isClosed: false },
    { name: 'Dot', title: 'Administrative Assistant IV', heartDiseases: 'English Walnut', lastVisit: 'Grollmann', isClosed: false },
    { name: 'Carol', title: 'Budget/Accounting Analyst IV', heartDiseases: 'Silver Citrate', lastVisit: 'Whybray', isClosed: true },
    { name: 'Zitella', title: 'Senior Sales Associate', heartDiseases: 'CEFUROXIME AND DEXTROSE', lastVisit: 'Husbands', isClosed: true },
    { name: 'Ulric', title: 'Director of Sales', heartDiseases: 'ONDANSETRON', lastVisit: 'Dodridge', isClosed: true },
    { name: 'Pate', title: 'Information Systems Manager', heartDiseases: 'CHLOROPROCAINE HYDROCHLORIDE', lastVisit: 'Renison', isClosed: true },
    { name: 'Helenelizabeth', title: 'Senior Editor', heartDiseases: 'Sodium Chloride, Sodium Lactate, Potassium Chloride, and Calcium Chloride', lastVisit: 'Arboin', isClosed: false },
    { name: 'Beniamino', title: 'Nuclear Power Engineer', heartDiseases: 'Argatroban', lastVisit: 'Kenny', isClosed: true },
    { name: 'Bev', title: 'Accountant IV', heartDiseases: 'dimethicone', lastVisit: 'Wikey', isClosed: false },
    { name: 'Ginger', title: 'Structural Analysis Engineer', heartDiseases: 'Norethindrone and Ethinyl Estradiol', lastVisit: 'Dreakin', isClosed: false },
    { name: 'Caleb', title: 'Cost Accountant', heartDiseases: 'temazepam', lastVisit: 'McCrudden', isClosed: false },
    { name: 'Sim', title: 'Payment Adjustment Coordinator', heartDiseases: 'Fludeoxyglucose F-18', lastVisit: 'Draycott', isClosed: true },
    { name: 'Danica', title: 'Computer Systems Analyst IV', heartDiseases: 'Pravastatin Sodium', lastVisit: 'Abbett', isClosed: true },
    { name: 'Gar', title: 'Administrative Assistant III', heartDiseases: 'MINERAL OIL', lastVisit: 'Pont', isClosed: true },
    { name: 'Vail', title: 'Marketing Assistant', heartDiseases: 'Treatment Set TS345883', lastVisit: 'Colbert', isClosed: false },
    { name: 'Viva', title: 'Professor', heartDiseases: 'Amoxicillin', lastVisit: 'Chisnall', isClosed: false },
    { name: 'Aldin', title: 'Analyst Programmer', heartDiseases: 'Tioconazole', lastVisit: 'Morin', isClosed: false },
    { name: 'Paulina', title: 'Recruiting Manager', heartDiseases: 'HYDROCORTISONE BUTYRATE', lastVisit: 'Reuven', isClosed: true },
    { name: 'Humfried', title: 'Registered Nurse', heartDiseases: 'Anticoagulant Citrate Dextrose Solution Formula A', lastVisit: 'McQuilkin', isClosed: false },
    { name: 'Ginny', title: 'Structural Engineer', heartDiseases: 'POTASSIUM CHLORIDE', lastVisit: 'Flinn', isClosed: true },
    { name: 'Cross', title: 'Quality Engineer', heartDiseases: 'bromocriptine mesylate', lastVisit: 'Prugel', isClosed: true },
    { name: 'Lusa', title: 'Administrative Assistant II', heartDiseases: 'Chelidonium Curcuma', lastVisit: 'Whifen', isClosed: false },
    { name: 'Kora', title: 'Statistician IV', heartDiseases: 'Anticoagulant Citrate Phosphate Dextrose Adenine (CPDA-1)', lastVisit: 'Kenwrick', isClosed: false },
    { name: 'Benedikt', title: 'Software Test Engineer I', heartDiseases: 'Coast Maple', lastVisit: 'Thrussell', isClosed: false },
    { name: 'Myrwyn', title: 'Media Manager I', heartDiseases: 'Trazodone Hydrochloride', lastVisit: 'Scouler', isClosed: false },
    { name: 'Mireielle', title: 'Geologist IV', heartDiseases: 'Lidocaine', lastVisit: 'Frede', isClosed: true },
    { name: 'Genia', title: 'Business Systems Development Analyst', heartDiseases: 'Salicylic Acid', lastVisit: 'Siward', isClosed: false },
    { name: 'Anstice', title: 'Marketing Manager', heartDiseases: 'CLOTRIMAZOLE', lastVisit: 'Pert', isClosed: true },
    { name: 'Rosetta', title: 'Compensation Analyst', heartDiseases: 'LYCOPODIUM CLAVATUM SPORE', lastVisit: 'Biskupek', isClosed: false },
    { name: 'Leora', title: 'Chemical Engineer', heartDiseases: 'Ensulizole, Octinoxate, Octocrylene, and Oxybenzone', lastVisit: 'Jefferson', isClosed: false },
    { name: 'Kahaleel', title: 'Safety Technician IV', heartDiseases: 'miconazole nitrate', lastVisit: 'Zanassi', isClosed: true },
    { name: 'Tomlin', title: 'Registered Nurse', heartDiseases: 'acetaminophen and codeine phosphate', lastVisit: 'Crighton', isClosed: true },
    { name: 'Geneva', title: 'Paralegal', heartDiseases: 'Ibuprofen', lastVisit: 'Infante', isClosed: true },
    { name: 'Joanne', title: 'Software Consultant', heartDiseases: 'Carvedilol', lastVisit: 'Load', isClosed: true },
    { name: 'Albrecht', title: 'Business Systems Development Analyst', heartDiseases: 'Alprazolam', lastVisit: 'Lambertson', isClosed: true },
    { name: 'Gianni', title: 'Cost Accountant', heartDiseases: 'ERYTHROMYCIN ETHYLSUCCINATE AND SULFISOXAZOLE ACETYL', lastVisit: 'Barnaby', isClosed: false },
    { name: 'Antonie', title: 'Professor', heartDiseases: 'Amlodipine Besylate', lastVisit: 'Notley', isClosed: false },
    { name: 'Clemence', title: 'Accountant II', heartDiseases: 'Methimazole', lastVisit: 'Feben', isClosed: true },
    { name: 'Tally', title: 'Web Developer I', heartDiseases: 'acetaminophen', lastVisit: 'Dudley', isClosed: true },
    { name: 'Danya', title: 'Marketing Manager', heartDiseases: 'Acetaminophen', lastVisit: 'Thynne', isClosed: true },
    { name: 'Ax', title: 'Pharmacist', heartDiseases: 'galantamine hydrobromide', lastVisit: 'Sukbhans', isClosed: true },
    { name: 'Emanuel', title: 'Technical Writer', heartDiseases: 'POVIDONE-IODINE', lastVisit: 'Bowcock', isClosed: true },
    { name: 'Nickie', title: 'Senior Quality Engineer', heartDiseases: 'AMMONIA N-13', lastVisit: 'Hatwell', isClosed: false },
    { name: 'Finley', title: 'Systems Administrator I', heartDiseases: 'Clotrimazole', lastVisit: 'Morphey', isClosed: false },
    { name: 'Sergent', title: 'Occupational Therapist', heartDiseases: 'Doxorubicin Hydrochloride', lastVisit: 'Leonards', isClosed: false },
    { name: 'Jehu', title: 'Health Coach III', heartDiseases: 'Heparin Sodium', lastVisit: 'Seleway', isClosed: true },
    { name: 'Jacky', title: 'Legal Assistant', heartDiseases: 'Pseudoephedrine HCl', lastVisit: 'Giorgeschi', isClosed: false },
    { name: 'Kimberli', title: 'Senior Quality Engineer', heartDiseases: 'Isosorbide Mononitrate', lastVisit: 'Ansell', isClosed: false },
    { name: 'Roseline', title: 'VP Product Management', heartDiseases: 'Prednisolone Sodium Phosphate', lastVisit: 'Micco', isClosed: true },
    { name: 'Ken', title: 'Compensation Analyst', heartDiseases: 'Lidocaine Hydrochloride and Epinephrine Bitartrate', lastVisit: 'Staddon', isClosed: true },
    { name: 'Wood', title: 'Analog Circuit Design manager', heartDiseases: 'Hydrocortisone', lastVisit: 'Boeck', isClosed: true },
    { name: 'Kinny', title: 'Marketing Manager', heartDiseases: 'Homeopathic Liquid', lastVisit: 'Churly', isClosed: false },
    { name: 'Vallie', title: 'Automation Specialist I', heartDiseases: 'Tacrolimus', lastVisit: 'Sharrem', isClosed: false },
    { name: 'Rance', title: 'Graphic Designer', heartDiseases: 'OCTINOXATE, HOMOSALATE, and AVOBENZONE', lastVisit: 'Gaggen', isClosed: true },
    { name: 'Lorraine', title: 'Editor', heartDiseases: 'Menthol and Methyl Salicylate', lastVisit: 'Rippon', isClosed: true },
    { name: 'Cymbre', title: 'Programmer Analyst II', heartDiseases: 'midodrine hydrochloride', lastVisit: 'Skally', isClosed: false },
    { name: 'Ethyl', title: 'Dental Hygienist', heartDiseases: 'Ramipril', lastVisit: 'Brumbie', isClosed: true },
    { name: 'Cordula', title: 'VP Sales', heartDiseases: 'Black Birch', lastVisit: 'Hodgon', isClosed: true },
    { name: 'Carmina', title: 'Structural Analysis Engineer', heartDiseases: 'ropinirole hydrochloride', lastVisit: 'Aubert', isClosed: false },
    { name: 'Antons', title: 'Nurse', heartDiseases: 'morphine sulfate', lastVisit: 'Acheson', isClosed: true },
    { name: 'Porter', title: 'Structural Analysis Engineer', heartDiseases: 'Triclosan', lastVisit: 'Menguy', isClosed: false },
    { name: 'Klaus', title: 'Account Coordinator', heartDiseases: 'Antiseptic hand wash', lastVisit: 'Welton', isClosed: true },
    { name: 'Rebecka', title: 'Marketing Manager', heartDiseases: 'Octinoxate and Titanium dioxide', lastVisit: 'Ricciardiello', isClosed: false },
    { name: 'Stefania', title: 'Accounting Assistant I', heartDiseases: 'dimethicone', lastVisit: 'Admans', isClosed: true },
    { name: 'Carole', title: 'Systems Administrator III', heartDiseases: 'enalaprilat', lastVisit: 'Bummfrey', isClosed: false },
    { name: 'Claudia', title: 'Senior Financial Analyst', heartDiseases: 'Allopurinol', lastVisit: 'Spiby', isClosed: true },
    { name: 'Justinn', title: 'Registered Nurse', heartDiseases: 'MANNITOL', lastVisit: 'Morris', isClosed: true },
    { name: 'Alfons', title: 'Help Desk Technician', heartDiseases: 'Quinapril', lastVisit: 'Wogan', isClosed: true },
    { name: 'Shalne', title: 'Human Resources Manager', heartDiseases: 'Metoprolol Succinate', lastVisit: 'Jaskiewicz', isClosed: false },
    { name: 'Egbert', title: 'GIS Technical Architect', heartDiseases: 'OCTINOXATE', lastVisit: 'Kemish', isClosed: true },
    {
        name: 'Dorothee',
        title: 'Research Nurse',
        heartDiseases:
            'Angelica sinensis radix, Arsenicum alb., Bryonia, Caulophyllum, Cimicifuga,Cinchona, Dioscorea, Folliculinum, Gelsemium, Lachesis, Lilium, Lycopodium, Millefolium, Nux vom., Pulsatilla, Sabina, Secale, Sepia, Thlaspi, Viburnum op., Zingiber, Echinacea, Valeriana',
        lastVisit: 'Reightley',
        isClosed: true,
    },
    { name: 'Selinda', title: 'Account Representative I', heartDiseases: 'Zinc Pyrithione', lastVisit: 'Ferie', isClosed: true },
    { name: 'Laurel', title: 'Physical Therapy Assistant', heartDiseases: 'ALCOHOL', lastVisit: 'Rodders', isClosed: false },
    { name: 'Gardie', title: 'Registered Nurse', heartDiseases: 'Lorazepam', lastVisit: 'Parnaby', isClosed: false },
    { name: 'Leonidas', title: 'Senior Cost Accountant', heartDiseases: 'Benazepril hydrochloride', lastVisit: 'Boarer', isClosed: false },
    { name: 'Whittaker', title: 'VP Quality Control', heartDiseases: 'TITANIUM DIOXIDE, ZINC OXIDE', lastVisit: 'Jakubovitch', isClosed: true },
    { name: 'Billie', title: 'Director of Sales', heartDiseases: 'ALCOHOL', lastVisit: 'Steinor', isClosed: false },
    { name: 'Clerc', title: 'Speech Pathologist', heartDiseases: 'Diclofenac Sodium', lastVisit: 'McGeachey', isClosed: false },
    { name: 'Yorgo', title: 'Computer Systems Analyst III', heartDiseases: 'Nitrous Oxide', lastVisit: 'Thistleton', isClosed: true },
    { name: 'Penn', title: 'Physical Therapy Assistant', heartDiseases: 'Lovastatin', lastVisit: 'Adlam', isClosed: true },
    { name: 'Marie', title: 'Senior Developer', heartDiseases: 'OCTINOXATE and TITANIUM DIOXIDE', lastVisit: 'Gameson', isClosed: true },
    { name: 'Gus', title: 'Sales Associate', heartDiseases: 'risperidone', lastVisit: 'Tesdale', isClosed: false },
    { name: 'Bria', title: 'Account Representative III', heartDiseases: 'Zinc Oxide', lastVisit: 'Mockett', isClosed: false },
    { name: 'Siusan', title: 'Clinical Specialist', heartDiseases: 'Hydrocortisone Valerate', lastVisit: 'Morling', isClosed: false },
    { name: 'Karin', title: 'Marketing Manager', heartDiseases: 'Tramadol hydrochloride and Acetaminophen', lastVisit: 'Mathouse', isClosed: false },
    { name: 'Jandy', title: 'Legal Assistant', heartDiseases: 'estradiol/norethindrone acetate', lastVisit: 'Bulter', isClosed: false },
    { name: 'Thayne', title: 'Financial Advisor', heartDiseases: 'Levetiracetam', lastVisit: 'Grayling', isClosed: false },
    { name: 'Harcourt', title: 'Operator', heartDiseases: 'moexipril hydrochloride and hydrochlorothiazide', lastVisit: 'Gaskamp', isClosed: true },
    { name: 'Vita', title: 'Health Coach I', heartDiseases: 'Urtica dioica', lastVisit: 'Basindale', isClosed: true },
    { name: 'Kizzee', title: 'Accounting Assistant I', heartDiseases: 'oxycodone hydrochloride and acetaminophen', lastVisit: 'Steptowe', isClosed: false },
    { name: 'Peterus', title: 'Nurse', heartDiseases: 'Sulfamethoxazole and Trimethoprim', lastVisit: 'McCartan', isClosed: false },
    { name: 'Bertie', title: 'Automation Specialist III', heartDiseases: 'Octinoxate and Avobenzone', lastVisit: 'Coveley', isClosed: false },
    { name: 'Rozelle', title: 'Quality Engineer', heartDiseases: 'Lansoprazole', lastVisit: 'Tunney', isClosed: true },
    { name: 'Aleta', title: 'Research Nurse', heartDiseases: 'valsartan and hydrochlorothiazide', lastVisit: 'Bau', isClosed: true },
    { name: 'Curr', title: 'Speech Pathologist', heartDiseases: 'SODIUM MONOFLUOROPHOSPHATE', lastVisit: 'Verralls', isClosed: false },
    { name: 'Lezlie', title: 'Biostatistician I', heartDiseases: 'antimonium tartaricum', lastVisit: 'Pomfrett', isClosed: true },
    { name: 'Sancho', title: 'Analog Circuit Design manager', heartDiseases: 'oxymetazoline hydrochloride', lastVisit: 'Willows', isClosed: false },
    { name: 'Dawna', title: 'Electrical Engineer', heartDiseases: 'White Petroleum', lastVisit: 'Diable', isClosed: false },
    { name: 'Geordie', title: 'Geologist IV', heartDiseases: 'AVOBENZONE, HOMOSALATE, OCTISALATE, OCTOCRYLENE, OXYBENZONE', lastVisit: 'Fifield', isClosed: true },
    { name: 'Homerus', title: 'VP Product Management', heartDiseases: 'Benzocaine', lastVisit: 'McClinton', isClosed: true },
    { name: 'Arthur', title: 'Senior Sales Associate', heartDiseases: 'Titanium Dioxide', lastVisit: 'Livesay', isClosed: true },
    { name: 'Levin', title: 'Compensation Analyst', heartDiseases: 'ESZOPICLONE', lastVisit: 'Slater', isClosed: true },
    { name: 'Rutledge', title: 'Business Systems Development Analyst', heartDiseases: 'fexofenadine hydrochloride', lastVisit: 'Meakes', isClosed: true },
    {
        name: 'Lauretta',
        title: 'Software Engineer I',
        heartDiseases: 'Histaminum hydrochloricum, Dopamine, Kidney, L-theanine, Penylethylamine hydrochloricum,',
        lastVisit: 'Brunstan',
        isClosed: false,
    },
    { name: 'Alyse', title: 'Software Test Engineer IV', heartDiseases: 'Fluoride', lastVisit: 'Gosselin', isClosed: false },
    { name: 'Gustavo', title: 'Sales Representative', heartDiseases: 'Antiseptic handwash', lastVisit: 'Pickover', isClosed: false },
    { name: 'Caroljean', title: 'Financial Analyst', heartDiseases: 'Calcitriol', lastVisit: 'Edwin', isClosed: false },
    {
        name: 'Sibyl',
        title: 'Sales Representative',
        heartDiseases: 'Vitamin A, Vitamin D, Thiamine, Riboflavin, Niacin, Pyridoxine, Folic Acid, Fluoride Ion, Ascorbic Acid, .Alpha.-Tocopherol-Acetate-DL, Cyanocobalamin',
        lastVisit: 'Fransman',
        isClosed: false,
    },
    { name: 'Grange', title: 'Geological Engineer', heartDiseases: 'Gabapentin', lastVisit: 'Alty', isClosed: true },
    { name: 'Olivia', title: 'Senior Cost Accountant', heartDiseases: 'DIMETHICONE', lastVisit: 'Abdy', isClosed: false },
    { name: 'Kingsley', title: 'Assistant Manager', heartDiseases: 'TITANIUM DIOXIDE', lastVisit: 'Chasemore', isClosed: false },
    {
        name: 'Gothart',
        title: 'Internal Auditor',
        heartDiseases:
            'ONION, APIS MELLIFERA, ATROPA BELLADONNA, EUPATORIUM PERFOLIATUM FLOWERING TOP, GELSEMIUM SEMPERVIRENS ROOT, POTASSIUM DICHROMATE, STRYCHNOS NUX-VOMICA SEED, PHYTOLACCA AMERICANA ROOT, PULSATILLA VULG',
        lastVisit: 'Vitet',
        isClosed: false,
    },
    { name: 'Alyosha', title: 'Speech Pathologist', heartDiseases: 'DEXTROSE MONOHYDRATE', lastVisit: 'Antognoni', isClosed: false },
    { name: 'Corrie', title: 'Registered Nurse', heartDiseases: 'PROPYLHEXEDRINE', lastVisit: 'Niaves', isClosed: true },
    { name: 'Adrianne', title: 'Quality Engineer', heartDiseases: 'Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone', lastVisit: 'Tunnicliffe', isClosed: false },
    {
        name: 'Christa',
        title: 'Account Executive',
        heartDiseases:
            'Anethum graveolens, Arnica montana, Asafoetida, Berberis aquifolium, Bismuthum metallicum, Calcarea phosphorica, Fagus sylvatica, flos, Ilex aquifolium, Lachesis mutus, Salix vitellina, flos, Sulphur, Zincum metallicum',
        lastVisit: 'Fewkes',
        isClosed: true,
    },
    { name: 'Loren', title: 'Tax Accountant', heartDiseases: 'ZINC OXIDE, ENSULIZOLE, POLYSILICONE-15, TITANIUM DIOXIDE, ATRACTYLODES JAPONICA ROOT OIL', lastVisit: 'Bartolacci', isClosed: true },
    { name: 'Norma', title: 'Administrative Officer', heartDiseases: 'INDIUM', lastVisit: 'Reichartz', isClosed: false },
    { name: 'Jacquette', title: 'Database Administrator II', heartDiseases: 'Hydroquinone, Octinoxate, and Zinc Oxide', lastVisit: 'Milstead', isClosed: false },
    { name: 'Danell', title: 'Chief Design Engineer', heartDiseases: 'Naproxen', lastVisit: 'Boteman', isClosed: true },
    { name: 'Patrice', title: 'VP Marketing', heartDiseases: 'Furosemide', lastVisit: 'Scanlin', isClosed: false },
    { name: 'Scarlet', title: 'Director of Sales', heartDiseases: 'Iloperidone', lastVisit: 'Farahar', isClosed: false },
    { name: 'Saidee', title: 'Accountant IV', heartDiseases: 'Benzocaine', lastVisit: 'Doughtery', isClosed: false },
    { name: 'Michal', title: 'Senior Cost Accountant', heartDiseases: 'Repaglinide', lastVisit: 'Roddell', isClosed: true },
    { name: 'Richy', title: 'Marketing Assistant', heartDiseases: 'ETHYL ALCOHOL', lastVisit: 'Songust', isClosed: false },
    { name: 'Marcellus', title: 'Senior Sales Associate', heartDiseases: 'Magnesium Chloride', lastVisit: 'Binyon', isClosed: true },
    { name: 'Cinda', title: 'Occupational Therapist', heartDiseases: 'AMLODIPINE BESYLATE TABLET', lastVisit: 'Follit', isClosed: false },
    { name: 'Diena', title: 'Recruiter', heartDiseases: 'Chloroquine Phosphate', lastVisit: 'Kleingrub', isClosed: false },
    { name: 'Blythe', title: 'Payment Adjustment Coordinator', heartDiseases: 'Benzalkonium Chloride', lastVisit: 'Kisar', isClosed: false },
    { name: 'Harriot', title: 'Pharmacist', heartDiseases: 'Norethindrone Acetate and Ethinyl Estradiol, and Ferrous Fumarate', lastVisit: 'Yushmanov', isClosed: false },
    { name: 'Tedd', title: 'Financial Advisor', heartDiseases: 'Firebush/Burning Bush', lastVisit: 'Vidyapin', isClosed: true },
    { name: 'Brewer', title: 'Administrative Officer', heartDiseases: 'SALICYLIC ACID', lastVisit: 'Cawkwell', isClosed: false },
    { name: 'Emmott', title: 'Automation Specialist III', heartDiseases: 'bupropion hydrochloride', lastVisit: 'Fatscher', isClosed: false },
    { name: 'Haze', title: 'Compensation Analyst', heartDiseases: 'Doxercalciferol', lastVisit: 'Sanchiz', isClosed: true },
    { name: 'Blanca', title: 'Accountant I', heartDiseases: 'phenytoin sodium', lastVisit: 'Keyson', isClosed: false },
    { name: 'Gloriane', title: 'Senior Quality Engineer', heartDiseases: 'Astragalus Arnica', lastVisit: 'Demead', isClosed: true },
    { name: 'Kelby', title: 'Quality Control Specialist', heartDiseases: 'Glyburide', lastVisit: 'Verry', isClosed: true },
    { name: 'Lissi', title: 'Executive Secretary', heartDiseases: 'Aluminum Zirconium Trichlorohydrex Gly', lastVisit: 'Panther', isClosed: false },
    { name: 'Abel', title: 'Assistant Manager', heartDiseases: 'TITANIUM DIOXIDE', lastVisit: 'Merkel', isClosed: true },
    { name: 'Kimball', title: 'Legal Assistant', heartDiseases: 'amaranthus retroflexus pollen', lastVisit: 'Allmond', isClosed: false },
    { name: 'Mona', title: 'Developer II', heartDiseases: 'equus caballus hair and equus caballus skin', lastVisit: 'Hentzer', isClosed: false },
    { name: 'Rey', title: 'Nuclear Power Engineer', heartDiseases: 'witch hazel', lastVisit: 'Bille', isClosed: true },
    { name: 'Ferne', title: 'Tax Accountant', heartDiseases: 'ursodiol', lastVisit: 'Simenon', isClosed: false },
    { name: 'Renado', title: 'Safety Technician IV', heartDiseases: 'MENTHOL', lastVisit: 'Snowball', isClosed: false },
    { name: 'Umberto', title: 'Recruiting Manager', heartDiseases: 'Triclosan', lastVisit: 'Kenwright', isClosed: false },
    { name: 'Cyndi', title: 'Technical Writer', heartDiseases: 'Benzocaine', lastVisit: 'Brugemann', isClosed: true },
    { name: 'Freida', title: 'Dental Hygienist', heartDiseases: 'NOT APPLICABLE', lastVisit: 'Blowen', isClosed: false },
    { name: 'Tynan', title: 'Design Engineer', heartDiseases: 'famotidine, calcium carbonate and magnesium hydroxide', lastVisit: 'McMains', isClosed: false },
    { name: 'Darby', title: 'Civil Engineer', heartDiseases: 'fentanyl transdermal system', lastVisit: 'Benneton', isClosed: false },
    {
        name: 'Erskine',
        title: 'Quality Control Specialist',
        heartDiseases: 'Allium cepa, Ambrosia artemisiaefolia, Apis mellifica, Arsenicum album, Euphrasia officinalis, Nux vomica, Phosphorus, Pulsatilla, Solidago virgaurea, Sulphur,',
        lastVisit: 'Hunt',
        isClosed: true,
    },
    { name: 'Hillel', title: 'Administrative Assistant II', heartDiseases: 'Pyrithione Zinc', lastVisit: 'Ruseworth', isClosed: true },
    { name: 'Dev', title: 'Accountant I', heartDiseases: 'OCTINOXATE, OXYBENZONE', lastVisit: 'McDonand', isClosed: true },
    { name: 'Floris', title: 'Computer Systems Analyst II', heartDiseases: 'TITANIUM DIOXIDE', lastVisit: 'MacAlpin', isClosed: true },
    { name: 'Onofredo', title: 'Nurse', heartDiseases: 'alcohol', lastVisit: 'Ebbings', isClosed: false },
    { name: 'Edith', title: 'Speech Pathologist', heartDiseases: 'Atenolol', lastVisit: 'McKiddin', isClosed: true },
    { name: 'Suzann', title: 'Marketing Assistant', heartDiseases: 'BENZOYL PEROXIDE', lastVisit: 'Tongue', isClosed: true },
    { name: 'Beaufort', title: 'Financial Analyst', heartDiseases: 'Benzocaine, Phenol, Camphor', lastVisit: 'Illston', isClosed: false },
    { name: 'Ric', title: 'Marketing Assistant', heartDiseases: 'vinCRIStine sulfate', lastVisit: 'Morriss', isClosed: false },
    { name: 'Agnes', title: 'Nuclear Power Engineer', heartDiseases: 'Nifedipine', lastVisit: 'Carpmile', isClosed: false },
    { name: 'Alic', title: 'Graphic Designer', heartDiseases: 'BENZOCAINE', lastVisit: 'Petford', isClosed: false },
    { name: 'Emogene', title: 'Marketing Manager', heartDiseases: 'Urea', lastVisit: 'Purslow', isClosed: true },
    { name: 'Franciska', title: 'Nuclear Power Engineer', heartDiseases: 'Phenytoin Sodium', lastVisit: 'Sharma', isClosed: true },
    { name: 'Truda', title: 'Engineer IV', heartDiseases: 'HYDROGEN PEROXIDE', lastVisit: 'Bassam', isClosed: true },
    { name: 'Esmaria', title: 'Mechanical Systems Engineer', heartDiseases: 'Morphine Sulfate', lastVisit: 'Cuncarr', isClosed: false },
    { name: 'Herve', title: 'Statistician IV', heartDiseases: 'Atenolol', lastVisit: 'McPhillips', isClosed: false },
    { name: 'Denys', title: 'Nurse', heartDiseases: 'IODINE, SODIUM IODIDE, ALCOHOL', lastVisit: 'Dicks', isClosed: false },
    { name: 'Mendel', title: 'Internal Auditor', heartDiseases: 'Quetiapine Fumarate', lastVisit: 'Romeuf', isClosed: false },
    { name: 'Marquita', title: 'GIS Technical Architect', heartDiseases: 'diltiazem hydrochloride', lastVisit: 'Crannach', isClosed: true },
    { name: 'Sabra', title: 'Data Coordiator', heartDiseases: 'Isosorbide Dinitrate', lastVisit: 'Zealander', isClosed: true },
    { name: 'Brianna', title: 'Automation Specialist I', heartDiseases: 'Prenatal Vitamins and Minerals Tablets', lastVisit: 'Kirkby', isClosed: true },
    { name: 'Sonny', title: 'Senior Editor', heartDiseases: 'A Mold Mixture', lastVisit: 'Lynd', isClosed: false },
    { name: 'Barthel', title: 'Web Developer IV', heartDiseases: 'Octinoxate and Titanium Dioxide', lastVisit: 'Arzu', isClosed: false },
    { name: 'Sandy', title: 'Legal Assistant', heartDiseases: 'MATRICARIA RECUTITA, RHUBARB, PHYTOLACCA AMERICANA ROOT', lastVisit: 'Pashley', isClosed: false },
    { name: 'Tressa', title: 'Nuclear Power Engineer', heartDiseases: 'Zaleplon', lastVisit: 'Vasenin', isClosed: false },
    { name: 'Alden', title: 'Account Representative I', heartDiseases: 'Sodium Fluoride Potassium Nitrate', lastVisit: 'Reicherz', isClosed: true },
    { name: 'Betti', title: 'Senior Quality Engineer', heartDiseases: 'Venlafaxine Hydrochloride', lastVisit: 'Gilchrest', isClosed: true },
    { name: 'Selig', title: 'Compensation Analyst', heartDiseases: 'Phentolamine Mesylate', lastVisit: 'Southall', isClosed: true },
    { name: 'Davon', title: 'Mechanical Systems Engineer', heartDiseases: 'OCTINOXATE, OCTISALATE', lastVisit: 'Bentham', isClosed: true },
    { name: 'Jackqueline', title: 'VP Quality Control', heartDiseases: 'Peach', lastVisit: 'Kingsford', isClosed: true },
    { name: 'Sheeree', title: 'Financial Advisor', heartDiseases: 'OCTINOXATE and TITANIUM DIOXIDE', lastVisit: 'Wolfart', isClosed: true },
    { name: 'Price', title: 'Health Coach III', heartDiseases: 'ethyl alcohol', lastVisit: 'Kalinsky', isClosed: true },
    { name: 'Nelie', title: 'Budget/Accounting Analyst II', heartDiseases: 'Ibuprofen', lastVisit: 'Betonia', isClosed: true },
    { name: 'Ive', title: 'Recruiting Manager', heartDiseases: 'benzalkonium chloride', lastVisit: 'Daoust', isClosed: true },
    { name: 'Odey', title: 'Human Resources Assistant III', heartDiseases: 'SALICYLIC ACID', lastVisit: 'Upcraft', isClosed: true },
    { name: 'Nelie', title: 'Physical Therapy Assistant', heartDiseases: 'Omeprazole Magnesium 20.6mg Capsules', lastVisit: 'Larimer', isClosed: false },
    { name: 'Waly', title: 'Food Chemist', heartDiseases: 'candida albicans', lastVisit: 'Fennelow', isClosed: false },
    { name: 'Salmon', title: 'Senior Financial Analyst', heartDiseases: 'diltiazem hydrochloride', lastVisit: 'Zaniolo', isClosed: false },
    { name: 'Loni', title: 'Programmer II', heartDiseases: 'Oxygen', lastVisit: 'Gosart', isClosed: false },
    { name: 'Windy', title: 'Developer III', heartDiseases: 'Lamivudine and Zidovudine', lastVisit: 'Janoch', isClosed: false },
    { name: 'Philippine', title: 'Structural Engineer', heartDiseases: 'Acetaminophine, caffeine', lastVisit: 'Astlatt', isClosed: false },
    { name: 'Mag', title: 'Programmer I', heartDiseases: 'Esomeprazole magnesium', lastVisit: 'Jancik', isClosed: false },
    { name: 'Roselle', title: 'General Manager', heartDiseases: 'Clonidine Hydrochloride', lastVisit: 'Caston', isClosed: true },
    { name: 'Deena', title: 'Sales Associate', heartDiseases: 'Olanzapine and Fluoxetine', lastVisit: 'Herion', isClosed: false },
    { name: 'Risa', title: 'Nurse', heartDiseases: 'methylphenidate hydrochloride', lastVisit: 'Stiddard', isClosed: false },
    { name: 'Maurits', title: 'Research Nurse', heartDiseases: 'Gabapentin', lastVisit: 'Fenemore', isClosed: false },
    { name: 'Ardenia', title: 'Programmer Analyst II', heartDiseases: 'Ipratropium Bromide', lastVisit: 'Pioch', isClosed: true },
    { name: 'Ennis', title: 'Biostatistician II', heartDiseases: 'Ethyl Alcohol', lastVisit: 'Loyd', isClosed: true },
    { name: 'Cathlene', title: 'Chief Design Engineer', heartDiseases: 'clobetasol propionate', lastVisit: 'Cannavan', isClosed: false },
    { name: 'Chuck', title: 'Research Assistant III', heartDiseases: 'Digoxin', lastVisit: 'Girling', isClosed: false },
    { name: 'Vasilis', title: 'Office Assistant I', heartDiseases: 'clonazepam', lastVisit: 'Trett', isClosed: false },
    { name: 'Romola', title: 'Geological Engineer', heartDiseases: 'Cefuroxime Axetil', lastVisit: 'Hugh', isClosed: false },
    { name: 'Alfred', title: 'VP Sales', heartDiseases: 'Chlorhexidine Gluconate', lastVisit: 'Lindenboim', isClosed: true },
    { name: 'Sarge', title: 'Accountant IV', heartDiseases: 'Dronedarone', lastVisit: 'Riggs', isClosed: false },
    { name: 'Berne', title: 'Developer IV', heartDiseases: 'Trifluoperazine Hydrochloride', lastVisit: 'Sumpner', isClosed: false },
    { name: 'Dagny', title: 'Legal Assistant', heartDiseases: 'imatinib mesylate', lastVisit: 'Senussi', isClosed: false },
    { name: 'Gardy', title: 'Pharmacist', heartDiseases: 'Promethazine Hydrochloride', lastVisit: 'Doers', isClosed: false },
    { name: 'Gaston', title: 'Programmer III', heartDiseases: 'quinapril hydrochloride and hydrochlorothiazide', lastVisit: 'Vedeneev', isClosed: false },
    { name: 'Mike', title: 'Assistant Manager', heartDiseases: 'Butabarbital Sodium', lastVisit: 'McInerney', isClosed: true },
    { name: 'Mehetabel', title: 'Associate Professor', heartDiseases: 'Acetaminophen, Diphenhydramine HCl', lastVisit: 'Fairfoot', isClosed: true },
    { name: 'Budd', title: 'Operator', heartDiseases: 'thrombin, topical (bovine)', lastVisit: 'Cullinane', isClosed: false },
    { name: 'Anna-diane', title: 'Director of Sales', heartDiseases: 'ZINC OXIDE and OCTINOXATE', lastVisit: 'Cisar', isClosed: false },
    { name: 'Cirstoforo', title: 'Occupational Therapist', heartDiseases: 'Bisoprolol Fumarate and Hydrochlorothiazide', lastVisit: 'Booy', isClosed: false },
    { name: 'Janela', title: 'Registered Nurse', heartDiseases: 'Benzoyl Peroxide', lastVisit: 'Valentinuzzi', isClosed: false },
    { name: 'Constantia', title: 'Internal Auditor', heartDiseases: 'Iodine Bush', lastVisit: 'Capineer', isClosed: false },
    {
        name: 'Madonna',
        title: 'Professor',
        heartDiseases:
            'Echinacea, Hydrastis canadensis, Phytolacca decandra, Alternaria tenuis, Aspergillus niger, Geotrichum candidum, Mucor racemosus, Pullularia pullulans, Rhizopus nigra, Acetaldehyde, Caffeic acid, Gallicum acidum,',
        lastVisit: 'Goodyer',
        isClosed: true,
    },
    { name: 'Jere', title: 'VP Product Management', heartDiseases: 'OCTINOXATE, TITANIUM DIOXIDE, OXYBENZONE', lastVisit: 'Snoxell', isClosed: true },
    { name: 'Brigitte', title: 'Safety Technician II', heartDiseases: 'Acetaminophen, Aspirin, Caffeine', lastVisit: 'Spoerl', isClosed: true },
    { name: 'Creigh', title: 'Executive Secretary', heartDiseases: 'Epinephrine', lastVisit: 'Trotman', isClosed: false },
    { name: 'Caye', title: 'Technical Writer', heartDiseases: 'Nortriptyline Hydrochloride', lastVisit: 'Lackeye', isClosed: false },
    { name: 'Sheelagh', title: 'Nurse Practicioner', heartDiseases: 'Acetaminophen, Dextromethorphan HBr, Phenylephrine HCl', lastVisit: 'Duffan', isClosed: false },
    { name: 'Colan', title: 'Office Assistant III', heartDiseases: 'Zinc Gluconate', lastVisit: 'Giovannoni', isClosed: true },
    { name: 'Irwin', title: 'Human Resources Assistant IV', heartDiseases: 'metoprolol tartrate', lastVisit: 'Satyford', isClosed: false },
    { name: 'Adelaide', title: 'Sales Associate', heartDiseases: 'Oxygen', lastVisit: 'Lente', isClosed: true },
    { name: 'Ardine', title: 'Dental Hygienist', heartDiseases: 'Isopropyl Alcohol', lastVisit: 'Hendrickson', isClosed: true },
    {
        name: 'Teddy',
        title: 'General Manager',
        heartDiseases: 'Apis mellifica, Belladonna, Calcarea carbonica, Medusa, Mezereum, Rhus toxicodendron, Astacus fluviatilis, Chloralum,',
        lastVisit: 'Pine',
        isClosed: false,
    },
    { name: 'Haily', title: 'Assistant Media Planner', heartDiseases: 'Potassium Chloride', lastVisit: 'Sleney', isClosed: true },
    { name: 'Lydia', title: 'VP Marketing', heartDiseases: 'Isopropyl Alcohol', lastVisit: 'Fowells', isClosed: false },
    { name: 'Merrile', title: 'Operator', heartDiseases: 'Naproxen', lastVisit: 'Wash', isClosed: true },
    { name: 'Dre', title: 'Staff Accountant III', heartDiseases: 'Brompheniramine Maleate, Dextromethorphan Hydrobromide and Phenylephrine Hydrochloride', lastVisit: 'Stonner', isClosed: false },
    { name: 'Terrel', title: 'Product Engineer', heartDiseases: 'Octinoxate, Octisalate, and Oxybenzone', lastVisit: 'Danaher', isClosed: true },
    { name: 'Tymon', title: 'Marketing Assistant', heartDiseases: 'Warfarin', lastVisit: 'Cominoli', isClosed: false },
    { name: 'Tabitha', title: 'Paralegal', heartDiseases: 'Montelukast Sodium', lastVisit: 'Ellsbury', isClosed: false },
    { name: 'Pearline', title: 'Help Desk Operator', heartDiseases: 'Pseudoephedrine Hydrochloride', lastVisit: 'Conman', isClosed: false },
    {
        name: 'Duff',
        title: 'Information Systems Manager',
        heartDiseases: 'SILICON DIOXIDE , SODIUM FLUORIDE, AMINOCAPROIC ACID, GLYCYRRHIZINATE DIPOTASSIUM, Curcuma xanthorrhiza oil, SEA SALT',
        lastVisit: 'Covotti',
        isClosed: true,
    },
    { name: 'Marlowe', title: 'Research Associate', heartDiseases: 'SODIUM FLUORIDE', lastVisit: 'Udell', isClosed: true },
    { name: 'Liane', title: 'Recruiter', heartDiseases: 'SELENIUM SULFIDE', lastVisit: 'Duly', isClosed: false },
    { name: 'Bunnie', title: 'Chief Design Engineer', heartDiseases: 'ZIPRASIDONE HYDROCHLORIDE', lastVisit: 'Gillham', isClosed: false },
    { name: 'Lynelle', title: 'Human Resources Assistant IV', heartDiseases: 'Potassium Chloride and Dextrose Monohydrate', lastVisit: 'Janicijevic', isClosed: false },
    { name: 'Adriaens', title: 'Clinical Specialist', heartDiseases: 'Phenol', lastVisit: 'Irdale', isClosed: false },
    { name: 'Vinny', title: 'Occupational Therapist', heartDiseases: 'Titanium Dioxide', lastVisit: 'Jonsson', isClosed: false },
    { name: 'Nicolea', title: 'Junior Executive', heartDiseases: 'SODIUM MONOFLUOROPHOSPHATE', lastVisit: 'Caldero', isClosed: false },
    { name: 'Mercie', title: 'Civil Engineer', heartDiseases: 'MENTHOL', lastVisit: "O'Hannigan", isClosed: true },
    { name: 'Jerrylee', title: 'Quality Control Specialist', heartDiseases: 'Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone', lastVisit: 'Hickinbottom', isClosed: true },
    { name: 'Francine', title: 'Nuclear Power Engineer', heartDiseases: 'mucor circinelloides f. lusitanicus', lastVisit: 'Espley', isClosed: true },
    { name: 'Corenda', title: 'Legal Assistant', heartDiseases: 'Avobenzone, Octisalate, and Octocrylene', lastVisit: 'Tellett', isClosed: false },
    { name: 'Karlie', title: 'Media Manager III', heartDiseases: 'BROMPHENIRAMINE MALEATE, CODEINE PHOSPHATE, and PSEUDOEPHEDRINE HYDROCHLORIDE', lastVisit: 'Tubbs', isClosed: false },
    { name: 'Maje', title: 'Help Desk Technician', heartDiseases: 'Lidocaine Hydrochloride', lastVisit: 'Glanester', isClosed: true },
    { name: 'Cassaundra', title: 'VP Sales', heartDiseases: 'ibuprofen', lastVisit: 'Duigenan', isClosed: false },
    {
        name: 'Octavius',
        title: 'Structural Engineer',
        heartDiseases: 'conium maculatum flowering top, sodium chloride, ruta graveolens flowering top and polygala senega root',
        lastVisit: 'Clendinning',
        isClosed: true,
    },
    { name: 'Augustus', title: 'Structural Engineer', heartDiseases: 'Carbamazepine', lastVisit: 'Robez', isClosed: true },
    { name: 'Tudor', title: 'Technical Writer', heartDiseases: 'Aspirin', lastVisit: 'Shackleford', isClosed: false },
    { name: 'Sharleen', title: 'Quality Engineer', heartDiseases: 'fluticasone propionate', lastVisit: 'Beccera', isClosed: true },
    { name: 'Hadria', title: 'Geological Engineer', heartDiseases: 'Hydrocortisone', lastVisit: 'Stinton', isClosed: false },
    { name: 'Edy', title: 'Computer Systems Analyst III', heartDiseases: 'Prednisone', lastVisit: 'Hollyland', isClosed: true },
    { name: 'Myrtie', title: 'Software Test Engineer II', heartDiseases: 'Albuterol Sulfate', lastVisit: 'Jecock', isClosed: true },
    { name: 'Deni', title: 'Biostatistician IV', heartDiseases: 'Alcohol', lastVisit: 'Rogers', isClosed: false },
    { name: 'Amandie', title: 'VP Product Management', heartDiseases: 'sulfacetamide sodium', lastVisit: 'Coupman', isClosed: true },
    { name: 'Alfons', title: 'Account Coordinator', heartDiseases: 'Ibuprofen', lastVisit: 'MacKaig', isClosed: false },
    { name: 'Izabel', title: 'Payment Adjustment Coordinator', heartDiseases: 'Hydroxychloroquine sulfate', lastVisit: 'Hingeley', isClosed: true },
    { name: 'Dehlia', title: 'Structural Analysis Engineer', heartDiseases: 'Glyburide', lastVisit: 'Wrigley', isClosed: true },
    { name: 'Immanuel', title: 'Account Representative II', heartDiseases: 'OCTINOXATE', lastVisit: 'Death', isClosed: true },
    { name: 'Ralph', title: 'Actuary', heartDiseases: 'Phenylephrine HCI', lastVisit: 'Nitto', isClosed: false },
    { name: 'Ase', title: 'Nurse Practicioner', heartDiseases: 'Black Walnut', lastVisit: 'Cordelette', isClosed: true },
    {
        name: 'Aube',
        title: 'Account Coordinator',
        heartDiseases: 'Calc. fluor., Calc. phos., Calc. sulph., Ferrum phosphoricum, Kali mur., Kali phos., Kali sulph., Mag. phos., Nat. mur., Nat. phos., Nat. sulphuricum, Silicea',
        lastVisit: 'Crossan',
        isClosed: false,
    },
    { name: 'Lyman', title: 'Paralegal', heartDiseases: 'Naproxen Sodium', lastVisit: 'Ketchell', isClosed: true },
    { name: 'Bartolemo', title: 'Design Engineer', heartDiseases: 'Isopropyl Alcohol', lastVisit: 'Maclean', isClosed: true },
    { name: 'Flinn', title: 'Actuary', heartDiseases: 'Articulatio Coxae 8', lastVisit: 'Downage', isClosed: false },
    { name: 'Delcine', title: 'Research Associate', heartDiseases: 'irinotecan hydrochloride', lastVisit: 'Borborough', isClosed: true },
    { name: 'Zebadiah', title: 'Recruiter', heartDiseases: 'neomycin sulfate, polymyxin b sulfate and dexamethasone', lastVisit: 'Rockhill', isClosed: false },
    { name: 'Katharine', title: 'Compensation Analyst', heartDiseases: 'abiraterone acetate', lastVisit: 'Bartoszewski', isClosed: false },
    { name: 'Tedd', title: 'Account Representative IV', heartDiseases: 'donepezil hydrochloride', lastVisit: 'Palliser', isClosed: false },
    { name: 'Dorthea', title: 'Programmer Analyst IV', heartDiseases: 'Acetaminophen', lastVisit: 'Korlat', isClosed: false },
    { name: 'Jo', title: 'Financial Advisor', heartDiseases: 'Lisinopril', lastVisit: 'Caswall', isClosed: true },
    { name: 'Angil', title: 'Civil Engineer', heartDiseases: 'ciprofloxacin hydrochloride', lastVisit: 'Swadlin', isClosed: true },
    { name: 'Ingeberg', title: 'Actuary', heartDiseases: 'Pork', lastVisit: 'Hawthorne', isClosed: false },
    { name: 'Cheslie', title: 'VP Accounting', heartDiseases: 'Paclitaxel', lastVisit: 'Ivers', isClosed: true },
    { name: 'Montgomery', title: 'Database Administrator II', heartDiseases: 'OXYGEN', lastVisit: 'Petrecz', isClosed: true },
    { name: 'Raquel', title: 'Office Assistant II', heartDiseases: 'SALICYLIC ACID', lastVisit: 'Vittery', isClosed: false },
    { name: 'Pandora', title: 'Director of Sales', heartDiseases: 'metronidazole', lastVisit: 'Edel', isClosed: true },
    { name: 'Mariel', title: 'Operator', heartDiseases: 'Amlodipine Besylate', lastVisit: 'Yuill', isClosed: true },
    { name: 'Dorey', title: 'Design Engineer', heartDiseases: 'Testosterone,', lastVisit: 'Pray', isClosed: true },
    { name: 'Maighdiln', title: 'GIS Technical Architect', heartDiseases: 'Amoxicillin and Clavulanate Potassium', lastVisit: 'Cowden', isClosed: false },
    { name: 'Fredrika', title: 'Teacher', heartDiseases: 'pioglitazone hydrochloride', lastVisit: 'Brotherhead', isClosed: true },
    { name: 'Prescott', title: 'Recruiting Manager', heartDiseases: 'ALUMINUM CHLOROHYDRATE', lastVisit: 'Afonso', isClosed: false },
    { name: 'Dorothea', title: 'Paralegal', heartDiseases: 'Proparacaine Hydrochloride', lastVisit: 'Hampstead', isClosed: false },
    { name: 'Ethyl', title: 'Recruiter', heartDiseases: 'Hydroxyzine Hydrochloride', lastVisit: 'Darby', isClosed: true },
    { name: 'Nial', title: 'Chief Design Engineer', heartDiseases: 'FERROSOFERRIC PHOSPHATE', lastVisit: 'Pinke', isClosed: true },
    { name: 'Daniele', title: 'Nurse', heartDiseases: 'Loratadine', lastVisit: 'Weall', isClosed: false },
    { name: 'Glenden', title: 'Senior Financial Analyst', heartDiseases: 'Ranitidine', lastVisit: 'Tames', isClosed: false },
    { name: 'Conrad', title: 'Compensation Analyst', heartDiseases: 'Calamine 8% and Zinc Oxide 8%', lastVisit: 'Amaya', isClosed: true },
    { name: 'Karee', title: 'Software Consultant', heartDiseases: 'Potassium Nitrate and Sodium Fluoride', lastVisit: 'Garbar', isClosed: false },
    { name: 'Cob', title: 'Community Outreach Specialist', heartDiseases: 'Triamterene and Hydrochlorothiazide', lastVisit: 'Jacqueminet', isClosed: true },
    { name: 'Cleveland', title: 'Accountant II', heartDiseases: 'dinoprostone', lastVisit: 'Rodder', isClosed: true },
    { name: 'Felisha', title: 'Actuary', heartDiseases: 'LIDOCAINE HYDROCHLORIDE', lastVisit: 'Barnet', isClosed: false },
    { name: 'Cyb', title: 'Editor', heartDiseases: 'OCTINOXATE,AVOBENZONE,OXYBENZONE', lastVisit: 'Housbey', isClosed: true },
    { name: 'Tim', title: 'Analog Circuit Design manager', heartDiseases: 'Escitalopram Oxalate', lastVisit: 'Petley', isClosed: false },
    { name: 'Jeddy', title: 'Office Assistant I', heartDiseases: 'TOPICAL STARCH', lastVisit: 'Goodfield', isClosed: true },
    { name: 'Chaunce', title: 'Web Developer III', heartDiseases: 'Atomoxetine Hydrochloride', lastVisit: 'Merrywether', isClosed: true },
    { name: 'Wanids', title: 'Quality Engineer', heartDiseases: 'SODIUM CHLORIDE', lastVisit: 'Daubney', isClosed: true },
    { name: 'Sibby', title: 'Civil Engineer', heartDiseases: 'Mineral Oil', lastVisit: 'Dmisek', isClosed: false },
    { name: 'Taddeusz', title: 'Staff Scientist', heartDiseases: 'Titanium Dioxide and Zinc oxide', lastVisit: 'Sanchiz', isClosed: false },
    { name: 'Sallyann', title: 'Health Coach II', heartDiseases: 'Loperamide HCl', lastVisit: 'Avrahamian', isClosed: true },
    { name: 'Ingemar', title: 'Librarian', heartDiseases: 'Aspirin', lastVisit: 'Lecordier', isClosed: true },
    { name: 'Gray', title: 'Assistant Manager', heartDiseases: 'Acetaminophen, Aspirin, Caffeine', lastVisit: 'Pizer', isClosed: true },
    {
        name: 'Mandel',
        title: 'VP Sales',
        heartDiseases: 'Hydrastis canadensis, Phytolacca decandra, Sarsaparilla, Xanthoxylum fraxineum, Aurum metallicum, Carbo animalis, Causticum, Iodium Sulphur, Thuja occidentalis,',
        lastVisit: 'Bottby',
        isClosed: true,
    },
    { name: 'Roderigo', title: 'VP Quality Control', heartDiseases: 'Oxygen', lastVisit: 'Widdall', isClosed: false },
    { name: 'Hyacinthie', title: 'Editor', heartDiseases: 'salicylic acid', lastVisit: 'Huard', isClosed: true },
    { name: 'Ara', title: 'Structural Analysis Engineer', heartDiseases: 'aspirin', lastVisit: 'Suggitt', isClosed: true },
    { name: 'Ethe', title: 'Senior Sales Associate', heartDiseases: 'Pulsatilla, Sepia, Euphrasia, Alumina, Arsenicum album, Nux mosch, Zincum m', lastVisit: 'Fernanando', isClosed: false },
    { name: 'Sigfried', title: 'Human Resources Assistant I', heartDiseases: 'Glycopyrrolate', lastVisit: 'Ryland', isClosed: true },
    { name: 'Ritchie', title: 'Quality Engineer', heartDiseases: 'Menthol', lastVisit: 'Sallans', isClosed: false },
    { name: 'Bryanty', title: 'Payment Adjustment Coordinator', heartDiseases: 'Fluoxetine Hydrochloride', lastVisit: 'Caro', isClosed: true },
    { name: 'Gabbi', title: 'Quality Control Specialist', heartDiseases: 'Carvedilol', lastVisit: 'Peddowe', isClosed: true },
    { name: 'Torie', title: 'Chemical Engineer', heartDiseases: 'acetaminophen, aspirin, and caffeine', lastVisit: 'Eathorne', isClosed: false },
    { name: 'Edgard', title: 'Biostatistician IV', heartDiseases: 'MENTHOL', lastVisit: 'Pele', isClosed: false },
    { name: 'Danny', title: 'Automation Specialist III', heartDiseases: 'Octinoxate', lastVisit: 'Trayling', isClosed: false },
    { name: 'Isiahi', title: 'Web Developer IV', heartDiseases: 'CUTTLEFISH', lastVisit: 'McNae', isClosed: true },
    { name: 'Massimiliano', title: 'Account Representative IV', heartDiseases: 'menthol', lastVisit: 'Borley', isClosed: false },
    { name: 'Cameron', title: 'Actuary', heartDiseases: 'ropinirole hydrochloride', lastVisit: 'Austen', isClosed: false },
    { name: 'Audrie', title: 'Engineer III', heartDiseases: 'Mirtazapine', lastVisit: 'Henrys', isClosed: false },
    { name: 'Robinia', title: 'Quality Engineer', heartDiseases: 'Triamterene and Hydrochlorothiazide', lastVisit: 'Lufkin', isClosed: true },
    { name: 'Hashim', title: 'Administrative Officer', heartDiseases: 'Oxaprozin', lastVisit: 'Barradell', isClosed: true },
    { name: 'Imogene', title: 'VP Product Management', heartDiseases: 'Atenolol', lastVisit: 'Manklow', isClosed: false },
    {
        name: 'Alis',
        title: 'Health Coach II',
        heartDiseases: 'Acetaminophen, Dextromethorphan hydrobromide, chlorpheniramine maleate, and pseudoephedrine Hydrochloride',
        lastVisit: 'Jebb',
        isClosed: true,
    },
    { name: 'Artur', title: 'Programmer II', heartDiseases: 'Alcohol', lastVisit: 'Schwaiger', isClosed: true },
    { name: 'Jsandye', title: 'VP Sales', heartDiseases: 'GLYCERIN', lastVisit: 'Durden', isClosed: true },
    { name: 'Heywood', title: 'Professor', heartDiseases: 'ANGOSTURA BARK', lastVisit: 'Schreiner', isClosed: true },
    { name: 'Merry', title: 'Web Designer IV', heartDiseases: 'carvedilol', lastVisit: 'Greenroad', isClosed: false },
    { name: 'Inge', title: 'Editor', heartDiseases: 'Octinoxate and Titanium Dioxide', lastVisit: 'Brennand', isClosed: true },
    { name: 'Bridie', title: 'Cost Accountant', heartDiseases: 'Gabapentin', lastVisit: 'McLaren', isClosed: true },
    { name: 'Randall', title: 'Electrical Engineer', heartDiseases: 'PETROLATUM', lastVisit: 'Daniellot', isClosed: false },
    { name: 'Tedman', title: 'Senior Cost Accountant', heartDiseases: 'Benzalkonium Chloride', lastVisit: 'Laurance', isClosed: true },
    { name: 'Terrill', title: 'General Manager', heartDiseases: 'Dimethicone', lastVisit: 'Calles', isClosed: true },
    { name: 'Shellie', title: 'Quality Control Specialist', heartDiseases: 'Acidulated Phosphate Fluoride', lastVisit: 'Waddup', isClosed: false },
    { name: 'Husein', title: 'Occupational Therapist', heartDiseases: 'bismuth subsalicylate', lastVisit: 'Matteuzzi', isClosed: false },
    { name: 'Diarmid', title: 'Web Designer II', heartDiseases: 'Paroxetine hydrochloride', lastVisit: 'Macey', isClosed: false },
    { name: 'Beret', title: 'Help Desk Technician', heartDiseases: 'Bacitracin Zinc, Neomycin Sulfate, Polymyxin B', lastVisit: 'Buncombe', isClosed: true },
    { name: 'Shell', title: 'Food Chemist', heartDiseases: 'oxycodone hydrochloride', lastVisit: 'Kamen', isClosed: true },
    { name: 'Louisette', title: 'Recruiter', heartDiseases: 'ibuprofen', lastVisit: 'Bortoletti', isClosed: true },
    { name: 'Jandy', title: 'Structural Engineer', heartDiseases: 'PYRITHIONE ZINC', lastVisit: 'Gabbett', isClosed: true },
    { name: 'Bink', title: 'Data Coordiator', heartDiseases: 'Ketorolac Tromethamine', lastVisit: 'Grandin', isClosed: true },
    { name: 'Nanni', title: 'Sales Representative', heartDiseases: 'Benazepril Hydrochloride', lastVisit: 'Boxe', isClosed: true },
    { name: 'Camilla', title: 'Structural Analysis Engineer', heartDiseases: 'linezolid', lastVisit: 'Sandle', isClosed: false },
    { name: 'Clem', title: 'Research Assistant III', heartDiseases: 'Oxygen', lastVisit: 'Birchill', isClosed: true },
    { name: 'Idelle', title: 'Analog Circuit Design manager', heartDiseases: 'Erythromycin', lastVisit: 'Scroggs', isClosed: false },
    { name: 'Coleman', title: 'Analyst Programmer', heartDiseases: 'East Sycamore', lastVisit: 'Howison', isClosed: false },
    { name: 'Winna', title: 'Software Consultant', heartDiseases: 'benzalkonium chloride', lastVisit: 'Bloxholm', isClosed: true },
    { name: 'Rosene', title: 'Assistant Professor', heartDiseases: 'Zonisamide', lastVisit: 'Volant', isClosed: true },
    { name: 'Cale', title: 'VP Accounting', heartDiseases: 'Ibuprofen', lastVisit: 'Tearney', isClosed: false },
    { name: 'Derick', title: 'Web Designer II', heartDiseases: 'Lidocaine Hydrochloride and Epinephrine Bitartrate', lastVisit: 'Pakenham', isClosed: true },
    { name: 'Ronnie', title: 'Legal Assistant', heartDiseases: 'Montelukast Sodium', lastVisit: 'Anfusso', isClosed: false },
    { name: 'Judy', title: 'Software Consultant', heartDiseases: 'fluvoxamine maleate', lastVisit: 'Blaine', isClosed: false },
    {
        name: 'Juditha',
        title: 'VP Sales',
        heartDiseases: 'Amino acids, Apis mellifica, Arnica montana, Fucus vesiculsus, Gambogia, Hepar suis, Phosphoricum acidum,',
        lastVisit: 'Waskett',
        isClosed: true,
    },
    { name: 'Delaney', title: 'Professor', heartDiseases: 'Psyllium Husk', lastVisit: 'Breffit', isClosed: true },
    { name: 'Joly', title: 'Database Administrator I', heartDiseases: 'Flaxseed', lastVisit: 'McPeake', isClosed: true },
    { name: 'Caroljean', title: 'Nurse Practicioner', heartDiseases: 'levetiracetam', lastVisit: 'Madre', isClosed: false },
    { name: 'William', title: 'Environmental Specialist', heartDiseases: 'Ailanthus', lastVisit: 'Bonnin', isClosed: false },
    { name: 'Jerri', title: 'Design Engineer', heartDiseases: 'OCTINOXATE', lastVisit: 'Gillino', isClosed: true },
    { name: 'Nancie', title: 'Biostatistician I', heartDiseases: 'vardenafil hydrochloride', lastVisit: 'McCowen', isClosed: true },
    { name: 'Theresita', title: 'Payment Adjustment Coordinator', heartDiseases: 'Montelukast Sodium', lastVisit: 'Easom', isClosed: false },
    { name: 'Kelsey', title: 'Assistant Manager', heartDiseases: 'neomycin sulfate, polymyxin b sulfate and gramicidin', lastVisit: 'Bonnefin', isClosed: false },
    { name: 'Cherye', title: 'Compensation Analyst', heartDiseases: 'Titanium Dioxide', lastVisit: 'Grebbin', isClosed: true },
    { name: 'Karisa', title: 'Tax Accountant', heartDiseases: 'halobetasol propionate', lastVisit: 'Wringe', isClosed: false },
    { name: 'Aggi', title: 'Operator', heartDiseases: 'tobramycin', lastVisit: 'Blackesland', isClosed: true },
    { name: 'Dallas', title: 'Programmer Analyst IV', heartDiseases: 'Cocklebur', lastVisit: 'Saiger', isClosed: true },
    { name: 'Kort', title: 'Dental Hygienist', heartDiseases: 'DOCUSATE SODIUM, SENNOSIDES', lastVisit: 'Cromb', isClosed: true },
    { name: 'Bud', title: 'Software Engineer II', heartDiseases: 'Zinc Oxide, Titanium Dioxide', lastVisit: 'Greenhaugh', isClosed: false },
    { name: 'Haleigh', title: 'Programmer Analyst III', heartDiseases: 'Alteplase', lastVisit: 'Wherton', isClosed: true },
    { name: 'Louie', title: 'Marketing Manager', heartDiseases: 'ZINC OXIDE', lastVisit: 'Nelson', isClosed: true },
    { name: 'Derby', title: 'Tax Accountant', heartDiseases: 'cocoa butter, phenylephrine hcl', lastVisit: 'Read', isClosed: false },
    { name: 'Donielle', title: 'Legal Assistant', heartDiseases: 'Azithromycin', lastVisit: 'Quincey', isClosed: true },
    { name: 'Whitman', title: 'Nuclear Power Engineer', heartDiseases: 'Octinoxate, Octisalate, and Oxybenzone', lastVisit: 'Scad', isClosed: true },
    { name: 'Sibeal', title: 'VP Quality Control', heartDiseases: 'Candida albicans', lastVisit: 'Scripture', isClosed: true },
    { name: 'Marina', title: 'Structural Analysis Engineer', heartDiseases: 'Acetaminophen', lastVisit: 'Wisedale', isClosed: true },
    { name: 'Lodovico', title: 'Mechanical Systems Engineer', heartDiseases: 'Antiperspirant and Deodorant', lastVisit: 'Sealeaf', isClosed: false },
    { name: 'Egon', title: 'Teacher', heartDiseases: 'Oxycodone and Acetaminophen', lastVisit: 'Pudan', isClosed: true },
    { name: 'Mayer', title: 'Teacher', heartDiseases: 'calcium carbonate', lastVisit: 'Kelson', isClosed: false },
    { name: 'Ilsa', title: 'Recruiter', heartDiseases: 'benzethonium chloride', lastVisit: 'Kyffin', isClosed: true },
    { name: 'Krysta', title: 'Database Administrator IV', heartDiseases: 'nitrofurantoin (macrocrystals)', lastVisit: 'Padginton', isClosed: true },
    { name: 'Richie', title: 'Analog Circuit Design manager', heartDiseases: 'atorvastatin calcium trihydrate', lastVisit: 'Ruffle', isClosed: false },
    { name: 'Thom', title: 'Occupational Therapist', heartDiseases: 'Trihexyphenidyl Hydrochloride', lastVisit: 'Ausher', isClosed: false },
    { name: 'Deanne', title: 'Environmental Specialist', heartDiseases: 'PANCRELIPASE', lastVisit: 'Lindeberg', isClosed: false },
    { name: 'Maryrose', title: 'Office Assistant IV', heartDiseases: 'Ondansetron Hydrochloride', lastVisit: 'Catto', isClosed: false },
    { name: 'Tadio', title: 'Senior Sales Associate', heartDiseases: 'Lisinopril and hydrochlorothiazide', lastVisit: 'Sjollema', isClosed: true },
    { name: 'Sam', title: 'Tax Accountant', heartDiseases: 'Mineral Oil, Petrolatum, Phenylephrine Hydrochloride', lastVisit: 'Jakubovicz', isClosed: false },
    { name: 'Gretel', title: 'Staff Scientist', heartDiseases: 'olmesartan medoxomil', lastVisit: 'Pantry', isClosed: false },
    { name: 'Aurilia', title: 'Structural Analysis Engineer', heartDiseases: 'Strawberry Fragaria chiloensis', lastVisit: 'Balfe', isClosed: true },
    { name: 'Gabi', title: 'Recruiter', heartDiseases: 'Pioglitazone Hydrochloride', lastVisit: 'Glowacha', isClosed: false },
    { name: 'Baxter', title: 'Analog Circuit Design manager', heartDiseases: 'Desoximetasone', lastVisit: 'Mose', isClosed: false },
    { name: 'Jeremie', title: 'Financial Analyst', heartDiseases: 'Midazolam', lastVisit: 'Korda', isClosed: false },
    { name: 'Blondy', title: 'Programmer Analyst III', heartDiseases: 'TRICLOSAN', lastVisit: 'Wolffers', isClosed: true },
    { name: 'Noll', title: 'Structural Analysis Engineer', heartDiseases: 'oxymorphone hydrochloride', lastVisit: 'Leuren', isClosed: false },
]
function setMockData() {
    for (let item of data) {
        item.description = ''
        item.bmi = 'индекс массы тела тест'
        item.bp = 'давление тест'
        item.heartDiseases = item.heartDiseases.slice(0, 20)
        item.priority = randomPriority()
        item.doctor = randomDoctor()
        item.age = Math.floor(Math.random() * 100)
    }
}
setMockData()
function randomPriority() {
    const arr = ['Обычная', 'Приоритетная', 'Неотложная']
    const rand = Math.floor(Math.random() * 3)
    return arr[rand]
}
function randomDoctor() {
    const arr = ['Кардиолог', 'Стоматолог', 'Терапевт']
    const rand = Math.floor(Math.random() * 3)
    return arr[rand]
}

// async function get() {
//     const response = await fetch('https://ajax.test-danit.com/api/v2/cards', {
//         method: 'GET',
//         headers: {
//             Authorization: `Bearer d6fcc7cd-ddeb-40b8-9cde-465a6f4c5ea3`,
//         },
//     })
//     const d = await response.json()
//     console.log(d)
// }
// get()
